### ISSUE TITLE
Oreberries 0.1.0 gives crash on server startup

### ISSUE THREAD

**Issue by digi-tal-it** [josephcsible/Oreberries#1]
When starting my mc 1.12.1 server, i get the following error from oreberries:

https://pastebin.com/uR6aqY9K

Minecraft 1.12.1
Forge 14.22.0.2475 (tested also with 14.22.0.2469)

**Comment by josephcsible** [comment]
Fixed in version 0.1.1 by ab131be.

**Comment by digi-tal-it** [comment]
Thanks for your quick help, now it works!
