### ISSUE TITLE
[1.12.2] Crash when berries get harvested by Quarry

### ISSUE THREAD

**Issue by DeadSix27** [josephcsible/Oreberries#10]
Log: https://0x0.st/sLpB.txt

As your mod get's listed first I reported it here, if you're sure it's the quarry mod's fault say so and I'll report it there.

**Comment by josephcsible** [comment]
I personally don't think it's my fault, but I can fix it on my side anyway.

(Edit: I opened Kotori316/QuarryPlus#21 with them, but you won't need to wait for it; my fix stands alone.)

**Comment by josephcsible** [comment]
Fixed in 0.4.1. If you don't want to wait for CurseForge to approve it, you can get it from https://github.com/josephcsible/Oreberries/releases/download/1.12.x-0.4.1/oreberries-1.12.x-0.4.1.jar
