### ISSUE TITLE
[Question]: Cobald and Ardite Berries 

### ISSUE THREAD

**Issue by lays24mc** [josephcsible/Oreberries#13]
Hi, 

I created in the oreberries.json Cobalt and Ardit (TConstuct) bushes. As far as everything works. Unfortunately, I realize now that I can craft the Oreberries to Cobalt Ingots and Ardit Ingots. Can I somehow disable that? I want the berries to be melted.

> "Cobalt": {
    "color": "#0e48c1",
    "tooltip": "Very rare",
    "smeltingResult": "tconstruct:nuggets",
    "rarity": 3,
	"density": 2,
    "maxHeight": 32,
    "sizeChance": 6,
	"replaceBlocks": ["minecraft:netherrack"],
	"dimensions": [-1]
  },
  "Ardite": {
    "color": "#CC3939",
    "tooltip": "Very rare",
    "smeltingResult": "tconstruct:nuggets:1",
    "rarity": 3,
	"density": 2,
    "maxHeight": 32,
    "sizeChance": 6,
	"replaceBlocks": ["minecraft:netherrack"],
	"dimensions": [-1]

**Comment by josephcsible** [comment]
This happens because oreberries are oredicted to nuggets by default, and the crafting recipe for cobalt and ardite ingots uses the oredict. To make this stop happening, add `"oredictNames": [],` to each of your entries.

**Comment by lays24mc** [comment]
Thank you. It works :D
