### ISSUE TITLE
[1.12.2] Crash ticking world [Unknown Source]

### ISSUE THREAD

**Issue by Draskh** [josephcsible/Oreberries#17]
I had a unknown crash, whilst I was travelling through the world. I post it to all mods that seems to be in the crash, maybe someone could find the bug. I had this crash several times. Same as https://github.com/Aang23/UndergroundBiomesConstructs/issues/3 and https://github.com/sp614x/optifine/issues/1837

See crash log for detailed mod information.

Could be related to https://github.com/sp614x/optifine/issues/1488 or https://github.com/iChun/IssueTracker-Mods/issues/61 

[crash-2018-09-27_01.21.51-client.txt](https://github.com/josephcsible/Oreberries/files/2421887/crash-2018-09-27_01.21.51-client.txt)
[crash-2018-09-27_01.20.49-server.txt](https://github.com/josephcsible/Oreberries/files/2421888/crash-2018-09-27_01.20.49-server.txt)

**Comment by josephcsible** [comment]
This is an issue with either UndergroundBiomes or NuclearCraft. I see you've already opened Aang23/UndergroundBiomesConstructs#3; ~~can you open a bug against NuclearCraft as well?~~ **EDIT: Now fixed by turbodiesel4598/NuclearCraft#366**.

Also, only the server crash report is important.

**Comment by josephcsible** [comment]
I confirmed this isn't actually related to Oreberries; see Aang23/UndergroundBiomesConstructs#3 and turbodiesel4598/NuclearCraft#366.
