### ISSUE TITLE
[Idea] Oreberry bushes don't drop anything when broken

### ISSUE THREAD

**Issue by BBoldt** [josephcsible/Oreberries#4]
I would like to encourage players to transport berries from the bush to their base, and not move the bush itself. Doesn't make much sense in a normal modpack, but I'm building one where it would be a fitting mechanic.

Also, i'm not requesting that the bushes be unbreakable, or even harder to break, just non transportable.

**Comment by josephcsible** [comment]
After reading both this and your other idea, I'm rather confused as to how exactly your modpack is going to work. Can you explain that in more detail?

**Comment by BBoldt** [comment]
So, a player discovers some berry bushes. All other ores are extremely rare. They really need this particular resource, but they can't just take it to their base, it becomes a logistics problem. The bushes would need to be harvested at the spot, and the drops would need to be slowly transported to the player's base using rails, pipes, or conveyors.

The idea of the pack is to encourage more long term logistics challenges, think Factorio.

**Comment by BBoldt** [comment]
Oh also, I would have it configured so more of them spawn near or on the surface. 
I'm not necessarily trying to make the game harder, just challenging in different ways.

**Comment by josephcsible** [comment]
Have you considered the mod [Bedrock Ores](https://mods.curse.com/mc-mods/minecraft/275083-bedrockores)? It seems to have both of the features you want (you can't move the ore source, and it eventually runs out).

**Comment by BBoldt** [comment]
Yeah, I have bedrock ores, I just thought this would be a good fit for a similar thing above ground.

I'm not requesting that the base mod be changed, just a config option. If you feel it's outside the scope or intention of this mod, feel free to close the issue.

**Comment by josephcsible** [comment]
Having thought about it, I am open to adding this as a setting. Would this still be useful to you without #5, though?

**Comment by BBoldt** [comment]
Yeah, that would be appreciated. I would just make them a bit more rare in the world.

The yield thing was just an idea. The main goal of the pack is just making logistics more of a challenge, and this setting is really all I need for that.

**Comment by josephcsible** [comment]
Okay. I plan to add the setting sometime this weekend.

**Comment by josephcsible** [comment]
Added to 0.3.0 in a307de2. Assuming you don't have any mods that let you get silk touch 2 somehow, just set the minimum silk touch level to 2 and it will do what you want. (If you do have such mods, then just set it to 1 higher than whatever the highest level they let you get is.)
