### ISSUE TITLE
[Idea] Maximum yield per bush

### ISSUE THREAD

**Issue by BBoldt** [josephcsible/Oreberries#5]
I would like to be able to set a maximum number a player can harvest from any specific bush. After the maximum amount has been reached, the bush would disappear.

**Comment by josephcsible** [comment]
Doesn't this kind of defeat the purpose of it being a bush then? Why not just have a regular ore that drops more than one thing?

**Comment by BBoldt** [comment]
I'm just trying to avoid most "neverending" ore types. 

Thematically it could work, in reality you could harvest a plant so much that it dies.

**Comment by josephcsible** [comment]
The whole point of this mod is to let you harvest unlimited ores from a bush given enough time. If it's not unlimited, how is it any different from regular worldgen ores?

**Comment by BBoldt** [comment]
It's different in that it could be potentially at the surface of a world, and could also have more output over time. 

Like I said on the other issue, i'm not trying to force you to do anything you don't want to, these are just suggestions. As the mod is currently, it doesn't really fit thematically in my pack yet is very close to fitting.

If you would rather just stick closer to only normal tconstruct-esque berry mechanics, that's fine.

**Comment by josephcsible** [comment]
Yeah, I really think this is out of scope for this mod. Sorry.
