### ISSUE TITLE
[Idea] Other dimensions config option

### ISSUE THREAD

**Issue by YOYOK9** [josephcsible/Oreberries#8]
Just an idea of adding a config that whitelists other dimensions added by mods to spawn oreberries. For example the Aroma1997's Dimensional world or the deep dark. 

Would allow pack makers more freedom on berry placement if for say they wanted players to go to different worlds for the berries.

**Comment by josephcsible** [comment]
This is already possible by setting "dimensions" in oreberries.json. See https://github.com/josephcsible/Oreberries/wiki/oreberries.json for details.

**Comment by YOYOK9** [comment]
you should give an example with where to put the dimension part. As it is not part of the .json by default, just an idea

**Comment by josephcsible** [comment]
I do, in the documentation page that I linked to.

**Comment by YOYOK9** [comment]
alright
